/**
 * Enum de erros tratados
 *
 * @enum {string}
 */
enum ExceptionEnum {
  EMAIL_DUPLICADO = 'EMAIL_DUPLICADO',
  USUARIO_INEXISTENTE = 'USUARIO_INEXISTENTE',
  EVENTO_INEXISTENTE = 'EVENTO_INEXISTENTE',
  PARTICIPANTE_DUPLICADO = 'PARTICIPANTE_DUPLICADO',
  PARTICIPANTE_INEXISTENTE = 'PARTICIPANTE_INEXISTENTE',
}

export default ExceptionEnum;
